### ISSUE TITLE
irreducibility assumption和data separability之间的区别？

### ISSUE THREAD

**Issue by Hengwei-Zhao96** [HC-Feynman/vpu#2]
你好，很感谢你出色的工作在PU学习方面，你在论文中提到了VPU不需要满足data separability，但是VPU需要满足irreducibility assumption，请问你能否在你方便的时候帮我解答一下二者（irreducibility assumption和data separability）之间的区别？

**Comment by HC-Feynman** [comment]
In short, data separability is a sufficient condition of irreducibility assumption.

Let’s call {x: f(x)>0} the support of f, denoted as supp(f). Data separability means supp(f_P) and supp(f_N) have an empty intersection. Irreducibility assumption refers that supp(f_P) is not a subset of supp(f_N), which is a quite weak assumption.

**Comment by Hengwei-Zhao96** [comment]
Thanks for your reply!
